### ISSUE TITLE
Deinitialize/unbind function?

### ISSUE THREAD

**Issue by janstieler** [nnattawat/slideReveal#10]
Hi,
is there an unbind or deinitialize function at the plugin?
I have an menu which is getting a sidebar if the window is resized to mobile but if I resize back actually I have only found the possibility to remove style
`.removeAttr('style');`
But if I make the window smaller again only the left attribut will work proper and no transition.

Kind regards

**Comment by nnattawat** [comment]
You cannot unbind it at the moment. I would suggest you use css `@medie` to override the CSS for the big screen or event hide the mobile panel.
