### ISSUE TITLE
Installation through Bower

### ISSUE THREAD

**Issue by Faiawuks** [nnattawat/slideReveal#12]
I am using Bower as my package manager, but I get an error when trying to install slideReveal. I can install any other package.

`bower install slidereveal`

and the result:

`bower ENOTFOUND     Request to https://bower.herokuapp.com/packages/slidereveal failed: getaddrinfo ENOTFOUND`

**Comment by nnattawat** [comment]
Thanks for reporting this. I have tested it and it worked for me. There might be a problem just for that time you run it.
