### ISSUE TITLE
problem with the 'width' option

### ISSUE THREAD

**Issue by Vendredi3** [nnattawat/slideReveal#3]
Hi,
I'm trying to use your plugin (which is great), but I'm facing a problem when I try to set the width.

See this fiddle : http://jsfiddle.net/rpf575qt/3/ 

with the default width (250), no problem. but when I set the width to 300, at the initialisation the "left" css property is set to -30000px, so my handle button is out of the viewport.

EDIT : 
using parseInt() at line 19 and 95 as below fix the problem : 

sidePosition = (parseInt(setting.width) + parseInt(paddingLeft) + parseInt(paddingRight)) + "px";

Thanks anyway

**Comment by LorenDorez** [comment]
@Vendredi3 Try putting the width without the qoutes, because with otherwise its a string.

```
$(document).ready(function(){
    $('#slider-hebergement').slideReveal({
        trigger: $(".handle"),
        width:300,
        push:false,
        position:'left'
    });
});
```

**Comment by nnattawat** [comment]
Thanks @LorenDorez for your reply :smile:

**Comment by Vendredi3** [comment]
Sorry for the delay, I'm just back from holidays... 
Thanks for your reply, I don't know why I haven't tried that before posting, it's so obvious... :no_mouth:
