### ISSUE TITLE
Custom close button

### ISSUE THREAD

**Issue by websmithinteractive** [nnattawat/slideReveal#4]
I have custom close button close button, but somehow I can't manage to close it
I'm new with jquery. I have an close icon and I did try

$('#slider').slideReveal("hide"{
  trigger: $("#cart-close")
});
 But it's not working, please tell me what am I doing wrong

**Comment by LorenDorez** [comment]
@cancerian73 Your above code looks to be incorrect. Try this to set your trigger. The "hide" shortcut is used manually to trigger the hide/show even from an button that is not set as the trigger

```
$("slider").slideReveal({
  trigger: $("#cart-close"),
});
```

**Comment by websmithinteractive** [comment]
Hi Loren
I'm sorry but where do I put the hide code?

**Comment by LorenDorez** [comment]
You should be able to chain then like this

```
$("slider").slideReveal({
  trigger: $("#cart-close"),
}),slideReveal("hide");
```

Or a cleaner looking way my be to return the object

```
var slider1 = $("slider").slideReveal({
  trigger: $("#cart-close"),
});

slider1.slideReveal("hide");
```

**Comment by nnattawat** [comment]
Thanks @LorenDorez for your reply
