### ISSUE TITLE
Make width option more flexible

### ISSUE THREAD

**Issue by nnattawat** [nnattawat/slideReveal#7]
Now `width` option can only receive `Integer`. It would be better to make it more flexible e.g. 100, '100', '100px', '80%'

**Comment by rolfsf** [comment]
This would be a nice enhancement - thanks!  A related issue is that the slideReveal panel does not respond to window resize event. So, due to fixed width and fixed position, sometimes a hidden panel appears (when window is resized smaller), or an open panel becomes wider than window.

**Comment by nnattawat** [comment]
I have fixed this issue on `v1.1.0`. Please update to the latest version and try. Use percentage width to make it responsive with window width.
